CREATE TABLE IF NOT EXISTS recipes (
  id SERIAL PRIMARY KEY, 
  name VARCHAR(255) NOT NULL, 
  ingredients TEXT NOT NULL, 
  directions TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  is_admin BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  item INTEGER REFERENCES recipes(id),
  author INTEGER REFERENCES users(id),
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(25) NOT NULL DEFAULT 'new'
);
